//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget
    {
        public int budget_id { get; set; }
        public int account_id { get; set; }
        public Nullable<int> fiscal_year { get; set; }
        public Nullable<decimal> allocated { get; set; }
        public Nullable<decimal> spent { get; set; }
        public Nullable<decimal> remaining { get; set; }
    
        public virtual account account { get; set; }
    }
}
