//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_items
    {
        public int item_id { get; set; }
        public int invoice_id { get; set; }
        public string description { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> tax_percent { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
