//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invoice_items = new HashSet<invoice_items>();
        }
    
        public int invoice_id { get; set; }
        public string customer_name { get; set; }
        public System.DateTime issue_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> tax_rate { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_items> invoice_items { get; set; }
    }
}
