//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPsystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPSYSTEMEntities : DbContext
    {
        public ERPSYSTEMEntities()
            : base("name=ERPSYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<budget> budgets { get; set; }
        public virtual DbSet<invoice_items> invoice_items { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
    }
}
